# Generated by Django 4.2.17 on 2024-12-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='example description'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lecture',
            field=models.TextField(default='example lecture'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
